### ISSUE TITLE
cli help is misguiding and broken

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/tracey-cli#4]
Let's pretend that I'm a tracey user. Readme doesn't really tell me how I supposed to invoke the tool so I follow CLI help

```
Andreys-MacBook-Pro:tracey-cli-rabbitmq andrey9kin$ java -jar ./build/libs/tracey-cli-rabbitmq.jar -h
usage: tracey [say | listen] (options)
options:

 -a <arg>    Host override
 -c <arg>    Configuration file
 -f          Specify this if the input is a file
 -h,--help   Prints help
 -p <arg>    Password override
 -u <arg>    Username override

Andreys-MacBook-Pro:tracey-cli-rabbitmq andrey9kin$ java -jar ./build/libs/tracey-cli-rabbitmq.jar say
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
    at java.util.LinkedList.get(LinkedList.java:476)
    at net.praqma.tracey.cli.Tracey.main(Tracey.java:100)

Andreys-MacBook-Pro:tracey-cli-rabbitmq andrey9kin$ java -jar ./build/libs/tracey-cli-rabbitmq.jar say hello
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
    at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
    at java.util.LinkedList.get(LinkedList.java:476)
    at net.praqma.tracey.cli.Tracey.main(Tracey.java:98)
```

A normal user will stop here. This is not good enough even for Alfa

Version used

```
Andreys-MacBook-Pro:tracey-cli-rabbitmq andrey9kin$ git rev-parse HEAD
4d1bb97c278dc5ee1b2d4c51fd83eaede494546e
```

Please use proper CLI parser and make sure that users get meaningful help when something is going wrong. It is critical that messenger is easy to use for a regular Joe otherwise no one will use it. Even us

**Comment by MadsNielsen** [comment]
@Andrey9kin Thanks for the bugreport. I'll see what i can do about it. In my testing i've only ever used it with the -c option and pointing to a configuration file. The built in options parser for Java is not very good. I'll try using the one you use in the eiffel message generator to see if it better.

**Comment by MadsNielsen** [comment]
Okay i dabbled with Argparse4j...i now have this message: 

```
D:\Programming\Projects\github\praqma\tracey-cli-rabbitmq\build\libs>java -jar tracey-cli-rabbitmq.jar -h
usage: tracey [-h] {say,listen} ...

Send message with Tracey. Using RabbitMQ

Run with arguments 'say -h' for help in sending messages.
Run with arguments 'listen -h' for help receiving messages

positional arguments:
  {say,listen}

optional arguments:
  -h, --help             show this help message and exit

D:\Programming\Projects\github\praqma\tracey-cli-rabbitmq\build\libs>java -jar tracey-cli-rabbitmq.jar say -h
usage: tracey say [-h] [-n NODE] [-e EXCHANGE] [-u USER] [-s SECRET]
              [-p PORT] [-c CONFIG] message

positional arguments:
  message

optional arguments:
  -h, --help             show this help message and exit
  -n NODE, --node NODE   The URL of the RabbitMQ server
  -e EXCHANGE, --exchange EXCHANGE
                         Exhange name (default: tracey)
  -u USER, --user USER   Username
  -s SECRET, --secret SECRET
                         Password
  -p PORT, --port PORT   Port
  -c CONFIG, --configure CONFIG
```
